# Generated by Django 4.2.16 on 2024-10-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zk_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
    ]
