# Generated by Django 4.2.16 on 2025-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlife',
            name='limit_life',
            field=models.IntegerField(verbose_name='Срок жизни'),
        ),
    ]
