# Generated by Django 4.2.16 on 2025-02-28 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tokenlife_limit_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlife',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
    ]
